# S#001 — Corpus Extraction (READ-ONLY). Prove the existing deterministic K'UHUL kernel can emit
# supervised semantic-trajectory training records — positive AND negative — WITHOUT inventing data
# and WITHOUT mutating any kernel source. The registries are the legality oracle:
#   phases.json valid_next  => legal traversals   (its complement => VIOLATION/invalid_traversal)
#   fold_definitions deps    => required inputs     (unmet => VIOLATION/dependency_missing)
# Emits 5 record classes (TRANSITION / DELTA / VIOLATION / INVARIANT / EQUIVALENCE) to JSONL.
#
# Reads only (never writes) the .ASX.cpp K'UHUL registries. Scaling to 10k+ records comes later
# from live FieldExecutionEngine traces; S#001 proves extraction from the static contracts.
import os, json, itertools

ASX = r"C:\Users\canna\.ASX.cpp"
PHASES = json.load(open(os.path.join(ASX, "kuhul-infrastructure", "registry", "phases.json")))["phases"]
FOLDS  = json.load(open(os.path.join(ASX, "kuhul-infrastructure", "folds", "fold_definitions.json")))["folds"]

recs = []
def R(**k): recs.append(k)
pid = {p["id"]: p for p in PHASES}
all_phases = [p["id"] for p in PHASES]

# 1) TRANSITION — legal state movement from phases.json valid_next (+ XCFE decision routes)
n=0
for p in PHASES:
    for nxt in (p.get("valid_next") or []):
        R(id=f"t{n:04d}", **{"class":"TRANSITION"}, state={"fold":p["id"], "have":p.get("inputs",[])},
          transition=f'{p["id"]}->{nxt}', next_state={"fold":nxt, "needs":pid.get(nxt,{}).get("inputs",[])},
          legality="legal", source="phases.json:valid_next"); n+=1
    for dec in p.get("decisions", []):
        route = dec.get("id");  tgt = dec.get("valid_next") or dec.get("next") or "Sek"
        R(id=f"t{n:04d}", **{"class":"TRANSITION"}, state={"fold":p["id"]}, transition=f'{p["id"]}::{route}',
          next_state={"fold":tgt}, legality="legal", source="phases.json:decisions"); n+=1

# 2) DELTA — a fold applied: before(inputs) + Δ(adds outputs) -> after ; legal per fold contract
for i,f in enumerate(FOLDS):
    ins, outs = f.get("inputs",[]), f.get("outputs",[])
    R(id=f"d{i:04d}", **{"class":"DELTA"}, field=f["id"], category=f.get("category"),
      before={"have":ins}, delta={"applies":f["id"], "adds":outs}, after={"have":ins+outs},
      legality="legal", source="fold_definitions:io")

# 3) VIOLATION — negatives, generated by the registry itself (the LegalityVerifier's ground truth)
n=0
for p in PHASES:                       # invalid_traversal = complement of valid_next
    legal = set(p.get("valid_next") or []) | {d.get("valid_next","Sek") for d in p.get("decisions",[])}
    for other in all_phases:
        if other != p["id"] and other not in legal:
            R(id=f"v{n:04d}", **{"class":"VIOLATION"}, state={"fold":p["id"]}, transition=f'{p["id"]}->{other}',
              legality="illegal", violation="invalid_traversal", expected_next=sorted(legal),
              source="phases.json:valid_next(complement)"); n+=1
for i,f in enumerate(FOLDS):           # dependency_missing = fold applied without its declared deps
    for dep in f.get("dependencies",[]):
        R(id=f"vd{i:03d}_{dep}", **{"class":"VIOLATION"}, field=f["id"], delta={"applies":f["id"]},
          legality="illegal", violation="dependency_missing", missing=dep,
          source="fold_definitions:dependencies"); n+=1

# 4) INVARIANT — what must NOT change: applying a fold appends outputs, preserves prior state (GROWING)
for i,f in enumerate(FOLDS):
    R(id=f"i{i:04d}", **{"class":"INVARIANT"}, field=f["id"], **{"preserve":f.get("inputs",[])},
      mutation="append", growth="outputs", note="prior state preserved; fold appends outputs (GROWING field)",
      source="fold_definitions:io")

# 5) EQUIVALENCE — different representations achieving the same transition (XCFE decision routes;
#    and folds of the same category producing similar outputs)
xcfe = pid.get("XCFE",{})
routes = [d.get("id") for d in xcfe.get("decisions",[])]
if routes:
    R(id="e0000", **{"class":"EQUIVALENCE"}, equivalence_class="xcfe_resolution",
      representations=routes, canonical={"transition":"Yax_validated -> Sek_ready"},
      note="distinct deltas achieving the same state transition", source="phases.json:XCFE.decisions")
from collections import defaultdict
bycat = defaultdict(list)
for f in FOLDS: bycat[f.get("category")].append(f["id"])
for cat, members in bycat.items():
    if len(members) > 1:
        R(id=f"e_{cat}", **{"class":"EQUIVALENCE"}, equivalence_class=f"category:{cat}",
          representations=members, canonical={"category":cat}, note="same semantic category",
          source="fold_definitions:category")

# write + report
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "semantic-trajectories.jsonl")
with open(OUT, "w", encoding="utf-8") as fo:
    for r in recs: fo.write(json.dumps(r) + "\n")

from collections import Counter
counts = Counter(r["class"] for r in recs)
print(f"[S#001] read-only extraction from phases.json ({len(PHASES)} phases) + fold_definitions.json ({len(FOLDS)} folds)")
for c in ["TRANSITION","DELTA","VIOLATION","INVARIANT","EQUIVALENCE"]:
    print(f"  {c:12s} {counts.get(c,0):4d}")
pos = sum(1 for r in recs if r.get('legality')=='legal'); neg = sum(1 for r in recs if r.get('legality')=='illegal')
print(f"  {'legal(pos)':12s} {pos:4d}\n  {'illegal(neg)':12s} {neg:4d}\n  {'TOTAL':12s} {len(recs):4d} -> {OUT}")
allfive = all(counts.get(c,0)>0 for c in ["TRANSITION","DELTA","VIOLATION","INVARIANT","EQUIVALENCE"])
print(f"=== {'PASS' if allfive and neg>0 else 'FAIL'}: S#001 corpus extraction — all 5 record classes emitted, positives AND negatives, kernel sources unmutated ===")
